### ISSUE TITLE
Documentation of Precision property

### ISSUE THREAD

**Issue by michaelhkay** [Singulink/Singulink.Numerics.BigDecimal#1]
The documentation says Precision is the total number of digits. Apparently it ignores trailing zeros, for example the precision of 123450000 is 5, not 9.

**Comment by mikernet** [comment]
Yeah, you can think of it as the number of digits when represented in scientific notation. I will clarify in the documentation, thanks for the report.

**Comment by mikernet** [comment]
Fixed in v1.0 release.
