### ISSUE TITLE
Round() with MidpointRoundingMode=ToPositiveInfinity fails

### ISSUE THREAD

**Issue by michaelhkay** [Singulink/Singulink.Numerics.BigDecimal#2]
Calling Round() with MidpointRoundingMode=ToPositiveInfinity fails saying the rounding mode is not supported. There is no hint of this in the documentation.

**Comment by michaelhkay** [comment]
In fact it seems that only ToEven and AwayFromZero are supported.

**Comment by mikernet** [comment]
Indeed, `netstandard` only supports those 2 rounding modes, the others were added to later framework versions. I can add support for the other rounding modes no problem if you need them.

**Comment by mikernet** [comment]
The other 3 modes are equivalent to `Truncate()/Floor()/Ceiling()`, which may meet your requirements if you just need to round to whole integers. I was planning to add support for the newer rounding modes regardless so I will do that within the next few days.

**Comment by michaelhkay** [comment]
Yes, the workaround is easy enough when dealing with whole numbers, but rounding to two decimal places is a bit trickier. I have to implement the semantics of round() in XPath 3.1.

**Comment by mikernet** [comment]
Negative digit counts aren't supported by the standard .NET numeric type rounding functions, but I'm not necessarily against adding that functionality to `BigDecimal`. From what I can tell, I think it should probably work without any functional code changes, just need to remove the range check from the `decimals` parameter, so wouldn't be difficult.

**Comment by mikernet** [comment]
Just tested it and the rounding code works just fine with negative values for the number of decimal places so I have removed the `< 0` check for that parameter and will include it in the next set of updates.

**Comment by mikernet** [comment]
Added support in v1.0 release.
