### ISSUE TITLE
Round-tripping double to decimal to double

### ISSUE THREAD

**Issue by michaelhkay** [Singulink/Singulink.Numerics.BigDecimal#4]
Consider:

```
            double d = 1e100 / 3;
            Console.WriteLine(d);
            BigDecimal dec = BigDecimal.FromDouble(d, false);
            Console.WriteLine((double)dec);
```
which outputs
```
3.333333333333333E+99
3.33333333333333E+99
```
I'm not sure whether there is a good reason to lose one digit of precision here. Although we've said we don't want an exact result, I would have expected enough precision to be retained to enable round-tripping.

**Comment by mikernet** [comment]
The decision to truncate at doubles at 15 digits and floats at 7 is inline with how .NET converts those values to `Decimal` values. Double's have 15 digits of "reliable" precision, and depending on how the value was calculated might eek out 1 or 2 more digits but they aren't particularly dependable. 

As per the spec, if a decimal string with at most 15 significant digits is converted to IEEE 754 double-precision representation, and then converted back to a decimal string with the same number of digits, the final result should match the original string. That doesn't necessarily hold for more than 15 significant digits though.

**Comment by mikernet** [comment]
If you want the option to specify a higher number of significant digits then I can make the method that takes in the number of digits public and you can specify a higher value if you like.

**Comment by mikernet** [comment]
You'll notice the same thing happens here:
```cs
            double d = 1.0 / 3;
            Console.WriteLine(d);
            Decimal dec = new Decimal(d);
            Console.WriteLine((double)dec);
```

**Comment by michaelhkay** [comment]
Another option would be to convert via string, since I've got an implementation of double-to-string that follows Guy L. Steele and Jon L. White, _How to Print Floating-Point Numbers Accurately_, ACM SIGPLAN 1990, which I guess is what I'm really looking for.

**Comment by mikernet** [comment]
How is that different than the regular `ToString()` implementation?

**Comment by mikernet** [comment]
It appears as though that is already the `ToString()` imlementation as per https://github.com/dotnet/runtime/blob/f7d48720a82920a4786e99b08c4687950c827896/src/libraries/System.Private.CoreLib/src/System/Number.Dragon4.cs#L109, so you could just use that and parse if you don't mind the performance hit.

**Comment by michaelhkay** [comment]
My code is all Java converted to C#, and I wrote this code because the Java double.toString() was badly broken at the time. Perhaps that's no longer the case, and/or I could switch to use the C# implementation in the C# version. But yes, I'm hesitant to do double-to-decimal via string for performance reasons.

**Comment by mikernet** [comment]
I just posted an update with all the new rounding modes plus better control over floating-point conversions - the nuget package should be indexed and available any minute. There are some minor breaking changes as the version has been updated to 2.0 but nothing that shouldn't take you 2 seconds to fix.
