### ISSUE TITLE
about trigonometric functions and other math functions support

### ISSUE THREAD

**Issue by CoreDX9** [Singulink/Singulink.Numerics.BigDecimal#5]
Do you plan to support trigonometric functions and other math functions like power or log？

**Comment by mikernet** [comment]
I've followed what Java's BigDecimal offers as that seems to cover the cases most people use this kind of data type for - it's not really intended as a general-purpose data type. There currently are `Pow` and `Pow10` functions constrained to parameters that make sense for arbitrary precision `BigDecimal` values. What is the use case for the other functions you are looking for? Do you really need more precision than is offered by other data types?

**Comment by mikernet** [comment]
I'm going to close this issue for now but feel free to follow up with answers to my questions if you wish to continue this discussion.
