### ISSUE TITLE
Issue with specic formual

### ISSUE THREAD

**Issue by AhmedMSedeek** [Singulink/Singulink.Numerics.BigDecimal#7]
Hello,

There's an issue when you try to assign specific formula result to a bigdecimal variable

C#
BigDecimal a = (decimal)0.4 / 3;

Then if you see the value of the variable (a) you get a very strange value, but if I change the value 0.4 to another value, it gets calculated correctly, don't know why this happens with specific value though

**Comment by mikernet** [comment]
Fixed via https://github.com/Singulink/Singulink.Numerics.BigDecimal/commit/bb29fdc023dd22b7e52ef6017c355422e497a77d.
