### ISSUE TITLE
Does it support hexadecimal large number calculation

### ISSUE THREAD

**Issue by qq1176914912** [Singulink/Singulink.Numerics.BigDecimal#9]
If Inscribe

**Comment by mikernet** [comment]
Not entirely sure what you mean. How would you represent a decimal with hex? You can convert the hex to BigInteger first and then cast to BigDecimal if you like.

**Comment by qq1176914912** [comment]
> Not entirely sure what you mean. How would you represent a decimal with hex? You can convert the hex to BigInteger first and then cast/assign that value to a BigDecimal if you like.
This is possible, but I still need to display the final result in hexadecimal. Does your method provide a method for ToByteArray() because I want to display it through the method of Hex.ToHexString

**Comment by mikernet** [comment]
Again, decimals can't really be represented as hex, that doesn't really make sense. Convert back to BigInteger when you're done and display that as hex.

**Comment by qq1176914912** [comment]
> Again, decimals can't really be represented as hex, that doesn't really make sense. Convert back to BigInteger when you're done and display that as hex.

I am asking this because I found that your method supports the same writing method as Microsoft, such as BigInteger. Parse (input1, System. Globalization. NumberStyles. HexNumber)

By using your method to replace BigInteger with BigDecimal:: BigDecimal. Parse (input1, System. Globalization. NumberStyles. HexNumber), there are no errors in the code, but an error will be reported during execution, indicating that hexadecimal is not supported

**Comment by mikernet** [comment]
Right, which is the same behavior as other built-in decimal-like types such as `decimal`, `float`, `double`, etc.

**Comment by mikernet** [comment]
Feel free to reply if you have any other questions but I will close the issue for now :)

**Comment by qq1176914912** [comment]
There is another issue, such as BigInteger. It can directly use BigInteger. Add, Subtract, Multiply, etc. I do not have this method when using your BigDecimal. What specific operations does your method BigDecimal support

**Comment by mikernet** [comment]
Operations are documented in [the docs](https://www.singulink.com/Docs/Singulink.Numerics.BigDecimal/api/Singulink.Numerics.BigDecimal.op_Addition.html)

**Comment by qq1176914912** [comment]
> Operations are documented in [the docs](https://www.singulink.com/Docs/Singulink.Numerics.BigDecimal/api/Singulink.Numerics.BigDecimal.op_Addition.html)

Thank you very much for your answer

**Comment by qq1176914912** [comment]
> Operations are documented in [the docs](https://www.singulink.com/Docs/Singulink.Numerics.BigDecimal/api/Singulink.Numerics.BigDecimal.op_Addition.html)

I'm very sorry to bother you again. It means that algorithms like addition and modulus don't need to be called in the way of BigDecimal.xxx, but can be directly connected with symbols? For example, addition: BigDecimal+BigDecimal multiplication is: BigDecimal * BigDecimal written like this?

**Comment by mikernet** [comment]
That's correct

**Comment by qq1176914912** [comment]
> That's correct

I see. I understand

**Comment by mikernet** [comment]
Note that there are many implicit conversions to BigDecimal, so you don't necessarily need to have 2 BigDecimal values. This works fine, for example:
```cs
BigDecimal x = 1234;
int y = 5678;

BigDecimal result = x + y;
```

**Comment by qq1176914912** [comment]
> Note that there are many implicit conversions to BigDecimal, so you don't necessarily need to have 2 BigDecimal values. This works fine, for example:
> 
> ```cs
> BigDecimal x = 1234;
> int y = 5678;
> 
> BigDecimal result = x + y;
> ```

Indeed, it is very convenient to write in this way. You have a comprehensive idea

**Comment by qq1176914912** [comment]
> Again, decimals can't really be represented as hex, that doesn't really make sense. Convert back to BigInteger when you're done and display that as hex.

Encountered a problem, due to the existence of division, it is impossible to guarantee that there will not be decimals in hexadecimal calculations. If this is the case, BigDecimal cannot be converted to BigInteger. Do you have any good solutions for this situation?

**Comment by mikernet** [comment]
What do you mean by "cannot be converted to BigInteger" - it can be converted fine, it just truncates the decimals. What behavior do you want?

**Comment by qq1176914912** [comment]
> What do you mean by "cannot be converted to BigInteger" - it can be converted fine, it just truncates the decimals. What behavior do you want?
Do you mean that when there are decimals, separate the numbers before and after the decimal point and convert them to BigInteger before concatenating them?, For example, in 1.2, would you first convert 1 to BigInteger, then convert 2 to BigInteger, and then reassemble the two with decimal points?

**Comment by mikernet** [comment]
Idk what you mean. Why are you converting to BigInteger if you are working with values like `1.2`? You only need to convert to BigInteger for hex parsing because hex decimals are not really a thing.

**Comment by mikernet** [comment]
I don't know what you are trying to achieve. If you have some weird hex format like `A1B2C3.FFFF` or something then yeah you will need to do some custom parsing and splitting to work with the two parts separately.

**Comment by qq1176914912** [comment]
> I don't know what you are trying to achieve. If you have some weird decimal hex format like `A1B2C3.FFFF` or something then yeah you will need to do some custom parsing and splitting to work with the two parts separately. Otherwise I don't know why you would convert to BigInteger.
I was influenced by the following image
![image](https://github.com/Singulink/Singulink.Numerics.BigDecimal/assets/79817742/29e67993-b562-4c32-a0ff-a3e39fc5e915)
I think so, I need to divide two large numbers by (a/b), and I use BigDecimal Parse converted these two numbers to BigDecimal type, and the final result must also be BigDecimal type. If I want to convert to hexadecimal display, I must first convert to BigInteger. You can see that the division in the figure above can display hexadecimal decimals, so I am a bit confused about how he did it

**Comment by qq1176914912** [comment]
Encountered a question about Pow, why does exponential not support negative numbers? Is this a bug or was it intentionally designed like this?
![image](https://github.com/Singulink/Singulink.Numerics.BigDecimal/assets/79817742/5ab35f73-c624-4c4d-8395-bef4f9a13f23)
![image](https://github.com/Singulink/Singulink.Numerics.BigDecimal/assets/79817742/07589e79-376f-4137-a255-2d88de9adc73)

**Comment by mikernet** [comment]
> Encountered a question about Pow, why does exponential not support negative numbers? Is this a bug or was it intentionally designed like this?

If you look at the method docs in intellisense or the docs site, you can see that this is intentional. Decimal types are not well suited for doing negative power calculations, that is generally in the realm of floating point types.

> I think so, I need to divide two large numbers by (a/b), and I use BigDecimal Parse converted these two numbers to BigDecimal type

If you are looking to mimic the behavior of that calculator, you are going to need to get into some rather obtuse mathematical concepts like working with numbers in different bases. Converting decimals in base 10 (i.e. in BigDecimal) to a base 16 (i.e. hex) representation is not trivial. It's not just a matter of converting the base 10 value after the decimal point to hex and tacking it on.

Github issues are not really suitable for this kind of chat. If you would like to continue this chat, please join our discord channel and we can talk there. It is linked at the top of the repo readme.

**Comment by qq1176914912** [comment]
> > Encountered a question about Pow, why does exponential not support negative numbers? Is this a bug or was it intentionally designed like this?
> 
> If you look at the method docs in intellisense or the docs site, you can see that this is intentional. Decimal types are not well suited for doing negative power calculations, that is generally in the realm of floating point types.
> 
> > I think so, I need to divide two large numbers by (a/b), and I use BigDecimal Parse converted these two numbers to BigDecimal type
> 
> If you are looking to mimic the behavior of that calculator, you are going to need to get into some rather obtuse mathematical concepts like working with numbers in different bases. Converting decimals in base 10 (i.e. in BigDecimal) to a base 16 (i.e. hex) representation is not trivial. It's not just a matter of converting the base 10 value after the decimal point to hex and tacking it on.
> 
> Github issues are not really suitable for this kind of chat. If you would like to continue this chat, please join our discord channel and we can talk there. It is linked at the top of the repo readme.

I'm sorry for the delay. Thank you for your patient answer. I have decided to give up the idea of converting decimals to hexadecimal and show that decimal is enough
